apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::XXXXXXXXXXXX:role/linkerd-cert-exp-check-role
    eks.amazonaws.com/sts-regional-endpoints: "true"
  name: cert-exp-check-sa
  namespace: devops
