apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.linkerd.namespace }}
  name: {{ .Values.role.name }}
{{ include "linkerd-cert-exp-check.labels" . | indent 2 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]